name: cleanup

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

env:
  REGISTRY: asia-southeast1-docker.pkg.dev
  APP_NAME: readit
  IMAGE_TAG_PREFIX: asia-southeast1-docker.pkg.dev/prj-c-readit-shared-infra-de69/container-repo-c-readit

jobs:
  docker-clean:
    runs-on: 'ubuntu-latest'
    permissions:
      # wif
      contents: read
      id-token: write
    steps:
      - name: Auth GCP Service Account
        id: auth-gcp
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
          access_token_lifetime: '1200s'

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth-gcp.outputs.access_token }}

      - uses: 'docker://asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo="${{ env.IMAGE_TAG_PREFIX }}/${{ env.APP_NAME }}-api"
            -repo="${{ env.IMAGE_TAG_PREFIX }}/${{ env.APP_NAME }}-pg-manager"
            -tag-filter-any=^(\d+).(\d+).(\d+)$
            -keep=30
