on:
  push:
    branches: [main]

jobs:
  dvc-code-usages:
    runs-on: ubuntu-latest
    name: Fetch DevCycle Code Usages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: DevCycleHQ/feature-flag-code-usage-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          client-id: ${{ secrets.DVC_CLIENT_ID }}
          client-secret: ${{ secrets.DVC_CLIENT_SECRET }}
          project-key: app-devcycle-com
