name: production

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: asia-southeast1-docker.pkg.dev
  IMAGE_TAG_PREFIX: asia-southeast1-docker.pkg.dev/prj-c-readit-shared-infra-de69/container-repo-c-readit
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  APP_NAME: readit
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: mplibunao
  TURBO_REMOTE_ONLY: true
  VERCEL_ORG_ID: Xl7cG8FFUpa6g9KEqzLz91Km
  VERCEL_PROJECT_ID: prj_fx8rZgSzOkAPc6w0T66BddkkpJcM

  API_HOST: 127.0.0.1
  DATABASE_URL: postgres://readit:postgres@localhost:5432/readit
  FRONTEND_URL: http://localhost:3000
  IS_PROD: false
  NODE_ENV: test
  PORT: 4000
  REDIS_URL: redis://:redis_password@localhost:6379
  TRPC_ENDPOINT: /trpc
  TRPC_PLAYGROUND_ENDPOINT: /trpc-playground

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >>$GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run CI
        run: |
          docker-compose up -d
          pnpm ci

  docker_prod_cd:
    name: docker_prod_cd
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      # wif
      contents: read
      id-token: write
    strategy:
      matrix:
        service: [api]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        id: auth-gcp
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          token_format: 'access_token'
          access_token_lifetime: '600s'

      - name: Build image tag
        run: |
          echo "IMAGE_TAG=${{ env.IMAGE_TAG_PREFIX }}/${{ env.APP_NAME }}-${{ matrix.service }}" >> $GITHUB_ENV
          echo "DOCKERFILE=./apps/${{ matrix.service }}/Dockerfile" >> $GITHUB_ENV

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        #with:
        #buildkitd-flags: --debug

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth-gcp.outputs.access_token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=${{ env.IMAGE_TAG }},enable=true
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=auto
            prefix=
            suffix=

      - name: Build and push
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: '${{ env.IMAGE_TAG }}:${{ steps.meta.outputs.version }}'
          service: readit-api
          region: asia-southeast1
          project_id: prj-p-readit-5ae4
          env_vars: |
            APP_VERSION=${{ steps.meta.outputs.version }}

  vercel_prod:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
