name: terraform_drift

defaults:
  run:
    shell: bash

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of terraform configuration
    strategy:
      matrix:
        directory:
          ['tf/applications/backend/0-folder', 'tf/applications/backend/prod']
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        id: auth-gcp
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          export_environment_variables: true
          create_credentials_file: true
          token_format: 'access_token'
          access_token_lifetime: '1200s'

      - name: Check
        uses: dflook/terraform-check@v1
        with:
          path: ${{ matrix.directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
